name: build-envoy-static

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: check cpu
      run: lscpu
    - name: check memory
      run: free -g
    - uses: actions/checkout@master
    - name: add bazel source
      run: echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - name: add bazel key
      run: curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - name: install bazel
      run: sudo apt-get update && sudo apt-get install bazel
    - name: install glib2.0
      run: sudo apt-get install libglib2.0-dev
    - name: install emsdk
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && cd -
    - name: add llvm repo
      run: cho "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" | sudo tee /etc/apt/sources.list.d/llvm.list
    - name: add llvm key
      run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - name: install llvm
      run: sudo apt-get install clang-8
    - name: install protobuf
      run: sudo apt install protobuf-compiler
    - name: install ninja-build
      run: sudo apt install ninja-build
    - name: compile envoy
      run: export CC=clang && export CXX=clang++ && ./emsdk/emsdk install latest && ./emsdk/emsdk activate latest && source ./emsdk/emsdk_env.sh && bazel build --define wasm=enabled --explain=~/bazel.log //source/exe:envoy-static
    - name: show files
      run: sudo apt install tree && tree -L 3
    - uses: actions/upload-artifact@master
      with:
        name: envoy-wasm
        path: ./bazel-envoy-wasm
