name: build-envoy-static

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: check cpu
      run: lscpu
    - name: check memory
      run: free -g
    - uses: actions/checkout@master
    - name: add bazel source
      run: echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - name: add bazel key
      run: curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - name: install bazel
      run: sudo apt-get update && sudo apt-get install bazel
    - name: install glib2.0
      run: sudo apt-get install libglib2.0-dev
    - name: install emsdk
      run: git clone https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && . ./emsdk_env.sh && cd -
    - name: add llvm repo
      run: cho "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" | sudo tee /etc/apt/sources.list.d/llvm.list
    - name: add llvm key
      run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - name: install llvm
      run: sudo apt-get install clang-8
    - name: install protobuf
      run: export CC=clang && export CXX=clang++ && git clone https://github.com/protocolbuffers/protobuf && cd protobuf && git checkout v3.6.1 && git submodule update --init --recursive && ./autogen.sh && ./configure && make && make check && sudo make install && cd -
